CREATE TABLE parcel
(
    ID                BIGSERIAL PRIMARY KEY,
    TYPE              VARCHAR(255),
    INDEX             VARCHAR(255),
    ADDRESS_RECIPIENT VARCHAR(255),
    NAME_RECIPIENT    VARCHAR(255),
    STATUS            VARCHAR(255)
);

CREATE TABLE post
(
    INDEX   VARCHAR(255) PRIMARY KEY,
    NAME    VARCHAR(255),
    ADDRESS VARCHAR(255)
);

CREATE TABLE history
(
    ID        BIGSERIAL PRIMARY KEY,
    PARCEL_ID BIGINT REFERENCES parcel (ID),
    STATUS    VARCHAR(255),
    DATE      TIMESTAMP
);